version: "3.6"

services:
  smart-brain-api:
    container_name: backend
    # image: node:14.17.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: shrey
      POSTGRES_PASSWORD: shreyx
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    links:
      - postgres
    ports:
      - "5000:3001"
    volumes:
      - ./:/usr/src/smart-brain-api

  #Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shrey
      POSTGRES_PASSWORD: shreyx
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
